// Interface automatically generated by schemas-to-ts

import { DownloadComponent } from '../../../../components/page/interfaces/DownloadComponent';
import { Technology } from '../../../technology/content-types/technology/technology';
import { Resourcy } from '../../../resourcy/content-types/resourcy/resourcy';
import { Product } from '../../../product/content-types/product/product';
import { DownloadComponent_Plain } from '../../../../components/page/interfaces/DownloadComponent';
import { Technology_Plain } from '../../../technology/content-types/technology/technology';
import { Resourcy_Plain } from '../../../resourcy/content-types/resourcy/resourcy';
import { Product_Plain } from '../../../product/content-types/product/product';
import { DownloadComponent_NoRelations } from '../../../../components/page/interfaces/DownloadComponent';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Download {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    downloads: DownloadComponent[];
    technology?: { data: Technology };
    resourcy?: { data: Resourcy };
    products?: { data: Product[] };
  };
}
export interface Download_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  downloads: DownloadComponent_Plain[];
  technology?: Technology_Plain;
  resourcy?: Resourcy_Plain;
  products?: Product_Plain[];
}

export interface Download_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  downloads: DownloadComponent_NoRelations[];
  technology?: number;
  resourcy?: number;
  products?: number[];
}

export interface Download_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  downloads: DownloadComponent_Plain[];
  technology?: AdminPanelRelationPropertyModification<Technology_Plain>;
  resourcy?: AdminPanelRelationPropertyModification<Resourcy_Plain>;
  products?: AdminPanelRelationPropertyModification<Product_Plain>;
}
