// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { Download } from '../../../download/content-types/download/download';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { Download_Plain } from '../../../download/content-types/download/download';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Technology {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    intro?: string;
    Technology?: any;
    EngineeringPrinciples?: any;
    IPRatings?: any;
    Manufacturing?: any;
    Certifications?: any;
    SeriesComparison?: any;
    Photometric?: any;
    Materials?: any;
    Downloads?: any;
    relatedDownload: { data: Download[] };
    FAQ?: any;
    EngineeringSupport?: any;
  };
}
export interface Technology_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  intro?: string;
  Technology?: any;
  EngineeringPrinciples?: any;
  IPRatings?: any;
  Manufacturing?: any;
  Certifications?: any;
  SeriesComparison?: any;
  Photometric?: any;
  Materials?: any;
  Downloads?: any;
  relatedDownload: Download_Plain[];
  FAQ?: any;
  EngineeringSupport?: any;
}

export interface Technology_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  intro?: string;
  Technology?: any;
  EngineeringPrinciples?: any;
  IPRatings?: any;
  Manufacturing?: any;
  Certifications?: any;
  SeriesComparison?: any;
  Photometric?: any;
  Materials?: any;
  Downloads?: any;
  relatedDownload: number[];
  FAQ?: any;
  EngineeringSupport?: any;
}

export interface Technology_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  intro?: string;
  Technology?: any;
  EngineeringPrinciples?: any;
  IPRatings?: any;
  Manufacturing?: any;
  Certifications?: any;
  SeriesComparison?: any;
  Photometric?: any;
  Materials?: any;
  Downloads?: any;
  relatedDownload: AdminPanelRelationPropertyModification<Download_Plain>;
  FAQ?: any;
  EngineeringSupport?: any;
}
