// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface CertificationItem {
  name?: string;
  image?: { data: Media };
  imageAlt?: string;
  title?: string;
  description?: string;
}
export interface CertificationItem_Plain {
  name?: string;
  image?: Media_Plain;
  imageAlt?: string;
  title?: string;
  description?: string;
}

export interface CertificationItem_NoRelations {
  name?: string;
  image?: number;
  imageAlt?: string;
  title?: string;
  description?: string;
}

