// Interface automatically generated by schemas-to-ts

import { DownloadItem } from '../../shared/interfaces/DownloadItem';
import { DownloadItem_Plain } from '../../shared/interfaces/DownloadItem';
import { DownloadItem_NoRelations } from '../../shared/interfaces/DownloadItem';

export interface DownloadComponent {
  name?: string;
  description?: string;
  downloads: DownloadItem[];
}
export interface DownloadComponent_Plain {
  name?: string;
  description?: string;
  downloads: DownloadItem_Plain[];
}

export interface DownloadComponent_NoRelations {
  name?: string;
  description?: string;
  downloads: DownloadItem_NoRelations[];
}

