// Interface automatically generated by schemas-to-ts

import { ItemFeature } from '../../shared/interfaces/ItemFeature';
import { ItemFeature_Plain } from '../../shared/interfaces/ItemFeature';
import { ItemFeature_NoRelations } from '../../shared/interfaces/ItemFeature';

export interface Features {
  feature: ItemFeature[];
}
export interface Features_Plain {
  feature: ItemFeature_Plain[];
}

export interface Features_NoRelations {
  feature: ItemFeature_NoRelations[];
}

