// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Hero {
  heroTitle?: string;
  heroDescription?: string;
  heroImage?: { data: Media };
  heroImageAlt?: string;
}
export interface Hero_Plain {
  heroTitle?: string;
  heroDescription?: string;
  heroImage?: Media_Plain;
  heroImageAlt?: string;
}

export interface Hero_NoRelations {
  heroTitle?: string;
  heroDescription?: string;
  heroImage?: number;
  heroImageAlt?: string;
}

