// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { ItemFeature } from '../../shared/interfaces/ItemFeature';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { ItemFeature_Plain } from '../../shared/interfaces/ItemFeature';
import { ItemFeature_NoRelations } from '../../shared/interfaces/ItemFeature';

export interface ImageTitle {
  name?: string;
  image?: { data: Media[] };
  imageAlt?: string;
  feature: ItemFeature[];
}
export interface ImageTitle_Plain {
  name?: string;
  image?: Media_Plain[];
  imageAlt?: string;
  feature: ItemFeature_Plain[];
}

export interface ImageTitle_NoRelations {
  name?: string;
  image?: number[];
  imageAlt?: string;
  feature: ItemFeature_NoRelations[];
}

