// Interface automatically generated by schemas-to-ts

export interface IpFeatures {
  info: IpFeatures[];
}
export interface IpFeatures_Plain {
  info: IpFeatures_Plain[];
}

export interface IpFeatures_NoRelations {
  info: IpFeatures_NoRelations[];
}

