// Interface automatically generated by schemas-to-ts

export enum Tag {
  Standard = 'standard',
  Premium = 'premium',
  Ultra = 'ultra',}

export interface SeriesSpecifications {
  name?: string;
  tag?: Tag;
  Chip_density?: string;
  CCT_range?: string;
  CRI?: string;
  Output?: string;
  IP_rating?: string;
  Cutting_length?: string;
  PCB_width?: string;
  Voltage?: string;
  Typical_application?: string;
}
export interface SeriesSpecifications_Plain {
  name?: string;
  tag?: Tag;
  Chip_density?: string;
  CCT_range?: string;
  CRI?: string;
  Output?: string;
  IP_rating?: string;
  Cutting_length?: string;
  PCB_width?: string;
  Voltage?: string;
  Typical_application?: string;
}

export interface SeriesSpecifications_NoRelations {
  name?: string;
  tag?: Tag;
  Chip_density?: string;
  CCT_range?: string;
  CRI?: string;
  Output?: string;
  IP_rating?: string;
  Cutting_length?: string;
  PCB_width?: string;
  Voltage?: string;
  Typical_application?: string;
}

