// Interface automatically generated by schemas-to-ts

import { HeroStat } from '../../home/interfaces/HeroStat';
import { HeroStat_Plain } from '../../home/interfaces/HeroStat';
import { HeroStat_NoRelations } from '../../home/interfaces/HeroStat';

export interface Stats {
  stat: HeroStat[];
}
export interface Stats_Plain {
  stat: HeroStat_Plain[];
}

export interface Stats_NoRelations {
  stat: HeroStat_NoRelations[];
}

