// Interface automatically generated by schemas-to-ts

import { Product } from '../../../product/content-types/product/product';
import { Product_Plain } from '../../../product/content-types/product/product';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Inquiry {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    firstName?: string;
    lastName?: string;
    email?: string;
    companyName?: string;
    phone?: string;
    country?: string;
    products: { data: Product[] };
    productSku?: string;
    message?: string;
    attachment?: string;
    sourceUrl?: string;
  };
}
export interface Inquiry_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  companyName?: string;
  phone?: string;
  country?: string;
  products: Product_Plain[];
  productSku?: string;
  message?: string;
  attachment?: string;
  sourceUrl?: string;
}

export interface Inquiry_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  companyName?: string;
  phone?: string;
  country?: string;
  products: number[];
  productSku?: string;
  message?: string;
  attachment?: string;
  sourceUrl?: string;
}

export interface Inquiry_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  email?: string;
  companyName?: string;
  phone?: string;
  country?: string;
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  productSku?: string;
  message?: string;
  attachment?: string;
  sourceUrl?: string;
}
