// Interface automatically generated by schemas-to-ts

export interface Btn {
  name?: string;
  link?: string;
}
export interface Btn_Plain {
  name?: string;
  link?: string;
}

export interface Btn_NoRelations {
  name?: string;
  link?: string;
}

