// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface DownloadItem {
  name?: string;
  title?: string;
  file?: { data: Media };
}
export interface DownloadItem_Plain {
  name?: string;
  title?: string;
  file?: Media_Plain;
}

export interface DownloadItem_NoRelations {
  name?: string;
  title?: string;
  file?: number;
}

