// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface Images {
  image?: { data: Media };
  isKey?: boolean;
  imageAlt?: string;
}
export interface Images_Plain {
  image?: Media_Plain;
  isKey?: boolean;
  imageAlt?: string;
}

export interface Images_NoRelations {
  image?: number;
  isKey?: boolean;
  imageAlt?: string;
}

