// Interface automatically generated by schemas-to-ts

export interface IpFeatures {
  name?: string;
  title?: string;
  description?: string;
}
export interface IpFeatures_Plain {
  name?: string;
  title?: string;
  description?: string;
}

export interface IpFeatures_NoRelations {
  name?: string;
  title?: string;
  description?: string;
}

