// Interface automatically generated by schemas-to-ts

export interface ItemFeature {
  title?: string;
  description?: string;
}
export interface ItemFeature_Plain {
  title?: string;
  description?: string;
}

export interface ItemFeature_NoRelations {
  title?: string;
  description?: string;
}

