// Interface automatically generated by schemas-to-ts

export interface NavLinkChild {
  label: string;
  href: string;
  description?: string;
}
export interface NavLinkChild_Plain {
  label: string;
  href: string;
  description?: string;
}

export interface NavLinkChild_NoRelations {
  label: string;
  href: string;
  description?: string;
}

