// Interface automatically generated by schemas-to-ts

import { NavLinkChild } from './NavLinkChild';
import { NavLinkChild_Plain } from './NavLinkChild';
import { NavLinkChild_NoRelations } from './NavLinkChild';

export interface NavLink {
  label: string;
  href: string;
  children: NavLinkChild[];
}
export interface NavLink_Plain {
  label: string;
  href: string;
  children: NavLinkChild_Plain[];
}

export interface NavLink_NoRelations {
  label: string;
  href: string;
  children: NavLinkChild_NoRelations[];
}

