// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface SeoMeta {
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string;
  ogImage?: { data: Media };
  ogImageAlt?: string;
  canonicalUrl?: string;
}
export interface SeoMeta_Plain {
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string;
  ogImage?: Media_Plain;
  ogImageAlt?: string;
  canonicalUrl?: string;
}

export interface SeoMeta_NoRelations {
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string;
  ogImage?: number;
  ogImageAlt?: string;
  canonicalUrl?: string;
}

