// Interface automatically generated by schemas-to-ts

export interface TagItem {
  label: string;
}
export interface TagItem_Plain {
  label: string;
}

export interface TagItem_NoRelations {
  label: string;
}

