// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Images } from '../../../../components/shared/interfaces/Images';
import { TrustBarItem } from '../../../../components/home/interfaces/TrustBarItem';
import { TagItem } from '../../../../components/shared/interfaces/TagItem';
import { ItemFeature } from '../../../../components/shared/interfaces/ItemFeature';
import { Product } from '../../../product/content-types/product/product';
import { HeroStat } from '../../../../components/home/interfaces/HeroStat';
import { SeoMeta } from '../../../../components/shared/interfaces/SeoMeta';
import { Category } from '../../../category/content-types/category/category';
import { ApplicationPage } from '../../../application-page/content-types/application-page/application-page';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Images_Plain } from '../../../../components/shared/interfaces/Images';
import { TrustBarItem_Plain } from '../../../../components/home/interfaces/TrustBarItem';
import { TagItem_Plain } from '../../../../components/shared/interfaces/TagItem';
import { ItemFeature_Plain } from '../../../../components/shared/interfaces/ItemFeature';
import { Product_Plain } from '../../../product/content-types/product/product';
import { HeroStat_Plain } from '../../../../components/home/interfaces/HeroStat';
import { SeoMeta_Plain } from '../../../../components/shared/interfaces/SeoMeta';
import { Category_Plain } from '../../../category/content-types/category/category';
import { ApplicationPage_Plain } from '../../../application-page/content-types/application-page/application-page';
import { Images_NoRelations } from '../../../../components/shared/interfaces/Images';
import { TrustBarItem_NoRelations } from '../../../../components/home/interfaces/TrustBarItem';
import { TagItem_NoRelations } from '../../../../components/shared/interfaces/TagItem';
import { ItemFeature_NoRelations } from '../../../../components/shared/interfaces/ItemFeature';
import { HeroStat_NoRelations } from '../../../../components/home/interfaces/HeroStat';
import { SeoMeta_NoRelations } from '../../../../components/shared/interfaces/SeoMeta';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Application {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    name?: string;
    slug?: string;
    description?: string;
    images: Images[];
    trust_bar: TrustBarItem[];
    longDescription?: string;
    tags: TagItem[];
    features: ItemFeature[];
    applications?: { data: Application[] };
    relatedApplication?: { data: Application[] };
    products?: { data: Product[] };
    results: HeroStat[];
    CTA?: any;
    seo?: SeoMeta;
    category?: { data: Category };
    application_page?: { data: ApplicationPage };
  };
}
export interface Application_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  name?: string;
  slug?: string;
  description?: string;
  images: Images_Plain[];
  trust_bar: TrustBarItem_Plain[];
  longDescription?: string;
  tags: TagItem_Plain[];
  features: ItemFeature_Plain[];
  applications?: Application_Plain[];
  relatedApplication?: Application_Plain[];
  products?: Product_Plain[];
  results: HeroStat_Plain[];
  CTA?: any;
  seo?: SeoMeta_Plain;
  category?: Category_Plain;
  application_page?: ApplicationPage_Plain;
}

export interface Application_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  name?: string;
  slug?: string;
  description?: string;
  images: Images_NoRelations[];
  trust_bar: TrustBarItem_NoRelations[];
  longDescription?: string;
  tags: TagItem_NoRelations[];
  features: ItemFeature_NoRelations[];
  applications?: number[];
  relatedApplication?: number[];
  products?: number[];
  results: HeroStat_NoRelations[];
  CTA?: any;
  seo?: SeoMeta_NoRelations;
  category?: number;
  application_page?: number;
}

export interface Application_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  name?: string;
  slug?: string;
  description?: string;
  images: Images_Plain[];
  trust_bar: TrustBarItem_Plain[];
  longDescription?: string;
  tags: TagItem_Plain[];
  features: ItemFeature_Plain[];
  applications?: AdminPanelRelationPropertyModification<Application_Plain>;
  relatedApplication?: AdminPanelRelationPropertyModification<Application_Plain>;
  products?: AdminPanelRelationPropertyModification<Product_Plain>;
  results: HeroStat_Plain[];
  CTA?: any;
  seo?: SeoMeta_Plain;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  application_page?: AdminPanelRelationPropertyModification<ApplicationPage_Plain>;
}
