// Interface automatically generated by schemas-to-ts

import { SpecGroup } from '../../../../components/product/interfaces/SpecGroup';
import { ProductPage } from '../../../product-page/content-types/product-page/product-page';
import { SpecGroup_Plain } from '../../../../components/product/interfaces/SpecGroup';
import { ProductPage_Plain } from '../../../product-page/content-types/product-page/product-page';
import { SpecGroup_NoRelations } from '../../../../components/product/interfaces/SpecGroup';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Spec {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    spec_group: SpecGroup[];
    product_page?: { data: ProductPage };
  };
}
export interface Spec_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  spec_group: SpecGroup_Plain[];
  product_page?: ProductPage_Plain;
}

export interface Spec_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  spec_group: SpecGroup_NoRelations[];
  product_page?: number;
}

export interface Spec_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  spec_group: SpecGroup_Plain[];
  product_page?: AdminPanelRelationPropertyModification<ProductPage_Plain>;
}
