// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { Spec } from '../../../spec/content-types/spec/spec';
import { Category } from '../../../category/content-types/category/category';
import { SeoMeta } from '../../../../components/shared/interfaces/SeoMeta';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { Spec_Plain } from '../../../spec/content-types/spec/spec';
import { Category_Plain } from '../../../category/content-types/category/category';
import { SeoMeta_Plain } from '../../../../components/shared/interfaces/SeoMeta';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { SeoMeta_NoRelations } from '../../../../components/shared/interfaces/SeoMeta';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ProductPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    specs: { data: Spec[] };
    categories: { data: Category[] };
    seo?: SeoMeta;
  };
}
export interface ProductPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  specs: Spec_Plain[];
  categories: Category_Plain[];
  seo?: SeoMeta_Plain;
}

export interface ProductPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  specs: number[];
  categories: number[];
  seo?: SeoMeta_NoRelations;
}

export interface ProductPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  specs: AdminPanelRelationPropertyModification<Spec_Plain>;
  categories: AdminPanelRelationPropertyModification<Category_Plain>;
  seo?: SeoMeta_Plain;
}
