// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { IpFeatures } from '../../../../components/page/interfaces/IpFeatures';
import { ItemFeature } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn } from '../../../../components/shared/interfaces/Btn';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { IpFeatures_Plain } from '../../../../components/page/interfaces/IpFeatures';
import { ItemFeature_Plain } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_Plain } from '../../../../components/shared/interfaces/Btn';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { IpFeatures_NoRelations } from '../../../../components/page/interfaces/IpFeatures';
import { ItemFeature_NoRelations } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_NoRelations } from '../../../../components/shared/interfaces/Btn';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ContactPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    address?: string;
    phone?: string;
    email?: string;
    working_hours?: string;
    salesInfo?: IpFeatures;
    inquiry?: ItemFeature;
    inquiry_btn?: Btn;
  };
}
export interface ContactPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  address?: string;
  phone?: string;
  email?: string;
  working_hours?: string;
  salesInfo?: IpFeatures_Plain;
  inquiry?: ItemFeature_Plain;
  inquiry_btn?: Btn_Plain;
}

export interface ContactPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  address?: string;
  phone?: string;
  email?: string;
  working_hours?: string;
  salesInfo?: IpFeatures_NoRelations;
  inquiry?: ItemFeature_NoRelations;
  inquiry_btn?: Btn_NoRelations;
}

export interface ContactPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  address?: string;
  phone?: string;
  email?: string;
  working_hours?: string;
  salesInfo?: IpFeatures_Plain;
  inquiry?: ItemFeature_Plain;
  inquiry_btn?: Btn_Plain;
}
