// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { Btn } from '../../../../components/shared/interfaces/Btn';
import { Stats } from '../../../../components/page/interfaces/Stats';
import { TrustBarItem } from '../../../../components/home/interfaces/TrustBarItem';
import { Category } from '../../../category/content-types/category/category';
import { Certification } from '../../../certification/content-types/certification/certification';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { Btn_Plain } from '../../../../components/shared/interfaces/Btn';
import { Stats_Plain } from '../../../../components/page/interfaces/Stats';
import { TrustBarItem_Plain } from '../../../../components/home/interfaces/TrustBarItem';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Certification_Plain } from '../../../certification/content-types/certification/certification';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { Btn_NoRelations } from '../../../../components/shared/interfaces/Btn';
import { Stats_NoRelations } from '../../../../components/page/interfaces/Stats';
import { TrustBarItem_NoRelations } from '../../../../components/home/interfaces/TrustBarItem';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface OverView {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    hero_tag?: string;
    hero_btn: Btn[];
    hero_stats: Stats[];
    hero_bar: TrustBarItem[];
    categories: { data: Category[] };
    page?: any;
    certifications: { data: Certification[] };
  };
}
export interface OverView_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  hero_tag?: string;
  hero_btn: Btn_Plain[];
  hero_stats: Stats_Plain[];
  hero_bar: TrustBarItem_Plain[];
  categories: Category_Plain[];
  page?: any;
  certifications: Certification_Plain[];
}

export interface OverView_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  hero_tag?: string;
  hero_btn: Btn_NoRelations[];
  hero_stats: Stats_NoRelations[];
  hero_bar: TrustBarItem_NoRelations[];
  categories: number[];
  page?: any;
  certifications: number[];
}

export interface OverView_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  hero_tag?: string;
  hero_btn: Btn_Plain[];
  hero_stats: Stats_Plain[];
  hero_bar: TrustBarItem_Plain[];
  categories: AdminPanelRelationPropertyModification<Category_Plain>;
  page?: any;
  certifications: AdminPanelRelationPropertyModification<Certification_Plain>;
}
