// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Product } from '../../../product/content-types/product/product';
import { SeoMeta } from '../../../../components/shared/interfaces/SeoMeta';
import { ProductPage } from '../../../product-page/content-types/product-page/product-page';
import { Application } from '../../../application/content-types/application/application';
import { OverView } from '../../../over-view/content-types/over-view/over-view';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Product_Plain } from '../../../product/content-types/product/product';
import { SeoMeta_Plain } from '../../../../components/shared/interfaces/SeoMeta';
import { ProductPage_Plain } from '../../../product-page/content-types/product-page/product-page';
import { Application_Plain } from '../../../application/content-types/application/application';
import { OverView_Plain } from '../../../over-view/content-types/over-view/over-view';
import { SeoMeta_NoRelations } from '../../../../components/shared/interfaces/SeoMeta';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Site {
  Cobflex = 'cobflex',}
export enum ProductOrApplication {
  Product = 'product',
  Application = 'application',}

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site?: Site;
    site_setting?: { data: SiteSetting };
    productOrApplication?: ProductOrApplication;
    name?: string;
    slug?: string;
    description?: string;
    image?: { data: Media };
    imageAlt?: string;
    order?: number;
    products: { data: Product[] };
    seo?: SeoMeta;
    product_page?: { data: ProductPage };
    applications: { data: Application[] };
    over_view_page?: { data: OverView };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site?: Site;
  site_setting?: SiteSetting_Plain;
  productOrApplication?: ProductOrApplication;
  name?: string;
  slug?: string;
  description?: string;
  image?: Media_Plain;
  imageAlt?: string;
  order?: number;
  products: Product_Plain[];
  seo?: SeoMeta_Plain;
  product_page?: ProductPage_Plain;
  applications: Application_Plain[];
  over_view_page?: OverView_Plain;
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site?: Site;
  site_setting?: number;
  productOrApplication?: ProductOrApplication;
  name?: string;
  slug?: string;
  description?: string;
  image?: number;
  imageAlt?: string;
  order?: number;
  products: number[];
  seo?: SeoMeta_NoRelations;
  product_page?: number;
  applications: number[];
  over_view_page?: number;
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site?: Site;
  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  productOrApplication?: ProductOrApplication;
  name?: string;
  slug?: string;
  description?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
  imageAlt?: string;
  order?: number;
  products: AdminPanelRelationPropertyModification<Product_Plain>;
  seo?: SeoMeta_Plain;
  product_page?: AdminPanelRelationPropertyModification<ProductPage_Plain>;
  applications: AdminPanelRelationPropertyModification<Application_Plain>;
  over_view_page?: AdminPanelRelationPropertyModification<OverView_Plain>;
}
