// Interface automatically generated by schemas-to-ts

export interface FooterContactInfo {
  address?: string;
  phone?: string;
  email?: string;
}
export interface FooterContactInfo_Plain {
  address?: string;
  phone?: string;
  email?: string;
}

export interface FooterContactInfo_NoRelations {
  address?: string;
  phone?: string;
  email?: string;
}

