// Interface automatically generated by schemas-to-ts

import { NavLink } from '../../shared/interfaces/NavLink';
import { NavLink_Plain } from '../../shared/interfaces/NavLink';
import { NavLink_NoRelations } from '../../shared/interfaces/NavLink';

export interface FooterColumn {
  title?: string;
  links: NavLink[];
}
export interface FooterColumn_Plain {
  title?: string;
  links: NavLink_Plain[];
}

export interface FooterColumn_NoRelations {
  title?: string;
  links: NavLink_NoRelations[];
}

