// Interface automatically generated by schemas-to-ts

export enum Platform {
  Linkedin = 'linkedin',
  Twitter = 'twitter',
  Youtube = 'youtube',
  Facebook = 'facebook',}

export interface SocialLink {
  platform?: Platform;
  url?: string;
}
export interface SocialLink_Plain {
  platform?: Platform;
  url?: string;
}

export interface SocialLink_NoRelations {
  platform?: Platform;
  url?: string;
}

