// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { Application } from '../../../application/content-types/application/application';
import { ItemFeature } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn } from '../../../../components/shared/interfaces/Btn';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { Application_Plain } from '../../../application/content-types/application/application';
import { ItemFeature_Plain } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_Plain } from '../../../../components/shared/interfaces/Btn';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { ItemFeature_NoRelations } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_NoRelations } from '../../../../components/shared/interfaces/Btn';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ApplicationPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    applications: { data: Application[] };
    cta?: ItemFeature;
    cta_btn?: Btn;
  };
}
export interface ApplicationPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  applications: Application_Plain[];
  cta?: ItemFeature_Plain;
  cta_btn?: Btn_Plain;
}

export interface ApplicationPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  applications: number[];
  cta?: ItemFeature_NoRelations;
  cta_btn?: Btn_NoRelations;
}

export interface ApplicationPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  applications: AdminPanelRelationPropertyModification<Application_Plain>;
  cta?: ItemFeature_Plain;
  cta_btn?: Btn_Plain;
}
