// Interface automatically generated by schemas-to-ts

export interface ProductSpecs {
  name: string;
  isKey?: boolean;
  value?: string;
}
export interface ProductSpecs_Plain {
  name: string;
  isKey?: boolean;
  value?: string;
}

export interface ProductSpecs_NoRelations {
  name: string;
  isKey?: boolean;
  value?: string;
}

