// Interface automatically generated by schemas-to-ts

import { ProductSpecs } from './ProductSpecs';
import { ProductSpecs_Plain } from './ProductSpecs';
import { ProductSpecs_NoRelations } from './ProductSpecs';

export interface SpecGroup {
  name?: string;
  spec: ProductSpecs[];
}
export interface SpecGroup_Plain {
  name?: string;
  spec: ProductSpecs_Plain[];
}

export interface SpecGroup_NoRelations {
  name?: string;
  spec: ProductSpecs_NoRelations[];
}

