// Interface automatically generated by schemas-to-ts

export interface HeroStat {
  value?: string;
  label?: string;
}
export interface HeroStat_Plain {
  value?: string;
  label?: string;
}

export interface HeroStat_NoRelations {
  value?: string;
  label?: string;
}

