// Interface automatically generated by schemas-to-ts

export interface TrustBarItem {
  icon?: string;
  label?: string;
  value?: string;
}
export interface TrustBarItem_Plain {
  icon?: string;
  label?: string;
  value?: string;
}

export interface TrustBarItem_NoRelations {
  icon?: string;
  label?: string;
  value?: string;
}

