// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Category } from '../../../category/content-types/category/category';
import { ItemFeature } from '../../../../components/shared/interfaces/ItemFeature';
import { Images } from '../../../../components/shared/interfaces/Images';
import { SpecGroup } from '../../../../components/product/interfaces/SpecGroup';
import { Download } from '../../../download/content-types/download/download';
import { Application } from '../../../application/content-types/application/application';
import { SeoMeta } from '../../../../components/shared/interfaces/SeoMeta';
import { Inquiry } from '../../../inquiry/content-types/inquiry/inquiry';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Category_Plain } from '../../../category/content-types/category/category';
import { ItemFeature_Plain } from '../../../../components/shared/interfaces/ItemFeature';
import { Images_Plain } from '../../../../components/shared/interfaces/Images';
import { SpecGroup_Plain } from '../../../../components/product/interfaces/SpecGroup';
import { Download_Plain } from '../../../download/content-types/download/download';
import { Application_Plain } from '../../../application/content-types/application/application';
import { SeoMeta_Plain } from '../../../../components/shared/interfaces/SeoMeta';
import { Inquiry_Plain } from '../../../inquiry/content-types/inquiry/inquiry';
import { ItemFeature_NoRelations } from '../../../../components/shared/interfaces/ItemFeature';
import { Images_NoRelations } from '../../../../components/shared/interfaces/Images';
import { SpecGroup_NoRelations } from '../../../../components/product/interfaces/SpecGroup';
import { SeoMeta_NoRelations } from '../../../../components/shared/interfaces/SeoMeta';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Badges {
  New = 'New',
  Hot = 'Hot',}

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    category?: { data: Category };
    model?: string;
    name?: string;
    slug?: string;
    isPick?: boolean;
    isAllPick?: boolean;
    badges?: Badges;
    features: ItemFeature[];
    images: Images[];
    spec_groups: SpecGroup[];
    downloads?: { data: Download[] };
    applications?: { data: Application[] };
    seo?: SeoMeta;
    inquiry?: { data: Inquiry };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  category?: Category_Plain;
  model?: string;
  name?: string;
  slug?: string;
  isPick?: boolean;
  isAllPick?: boolean;
  badges?: Badges;
  features: ItemFeature_Plain[];
  images: Images_Plain[];
  spec_groups: SpecGroup_Plain[];
  downloads?: Download_Plain[];
  applications?: Application_Plain[];
  seo?: SeoMeta_Plain;
  inquiry?: Inquiry_Plain;
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  category?: number;
  model?: string;
  name?: string;
  slug?: string;
  isPick?: boolean;
  isAllPick?: boolean;
  badges?: Badges;
  features: ItemFeature_NoRelations[];
  images: Images_NoRelations[];
  spec_groups: SpecGroup_NoRelations[];
  downloads?: number[];
  applications?: number[];
  seo?: SeoMeta_NoRelations;
  inquiry?: number;
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  model?: string;
  name?: string;
  slug?: string;
  isPick?: boolean;
  isAllPick?: boolean;
  badges?: Badges;
  features: ItemFeature_Plain[];
  images: Images_Plain[];
  spec_groups: SpecGroup_Plain[];
  downloads?: AdminPanelRelationPropertyModification<Download_Plain>;
  applications?: AdminPanelRelationPropertyModification<Application_Plain>;
  seo?: SeoMeta_Plain;
  inquiry?: AdminPanelRelationPropertyModification<Inquiry_Plain>;
}
