// Interface automatically generated by schemas-to-ts

import { CertificationItem } from '../../../../components/page/interfaces/CertificationItem';
import { OverView } from '../../../over-view/content-types/over-view/over-view';
import { CertificationItem_Plain } from '../../../../components/page/interfaces/CertificationItem';
import { OverView_Plain } from '../../../over-view/content-types/over-view/over-view';
import { CertificationItem_NoRelations } from '../../../../components/page/interfaces/CertificationItem';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Certification {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    certifications: CertificationItem[];
    over_view_page?: { data: OverView };
  };
}
export interface Certification_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  certifications: CertificationItem_Plain[];
  over_view_page?: OverView_Plain;
}

export interface Certification_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  certifications: CertificationItem_NoRelations[];
  over_view_page?: number;
}

export interface Certification_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  certifications: CertificationItem_Plain[];
  over_view_page?: AdminPanelRelationPropertyModification<OverView_Plain>;
}
