// Interface automatically generated by schemas-to-ts

import { SiteSetting } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero } from '../../../../components/page/interfaces/Hero';
import { Download } from '../../../download/content-types/download/download';
import { ItemFeature } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn } from '../../../../components/shared/interfaces/Btn';
import { SeoMeta } from '../../../../components/shared/interfaces/SeoMeta';
import { SiteSetting_Plain } from '../../../site-setting/content-types/site-setting/site-setting';
import { Hero_Plain } from '../../../../components/page/interfaces/Hero';
import { Download_Plain } from '../../../download/content-types/download/download';
import { ItemFeature_Plain } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_Plain } from '../../../../components/shared/interfaces/Btn';
import { SeoMeta_Plain } from '../../../../components/shared/interfaces/SeoMeta';
import { Hero_NoRelations } from '../../../../components/page/interfaces/Hero';
import { ItemFeature_NoRelations } from '../../../../components/shared/interfaces/ItemFeature';
import { Btn_NoRelations } from '../../../../components/shared/interfaces/Btn';
import { SeoMeta_NoRelations } from '../../../../components/shared/interfaces/SeoMeta';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Resourcy {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    site_setting?: { data: SiteSetting };
    hero?: Hero;
    intro?: string;
    note?: string;
    downloads: { data: Download[] };
    cta?: ItemFeature;
    cta_btn?: Btn;
    seo?: SeoMeta;
  };
}
export interface Resourcy_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: SiteSetting_Plain;
  hero?: Hero_Plain;
  intro?: string;
  note?: string;
  downloads: Download_Plain[];
  cta?: ItemFeature_Plain;
  cta_btn?: Btn_Plain;
  seo?: SeoMeta_Plain;
}

export interface Resourcy_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: number;
  hero?: Hero_NoRelations;
  intro?: string;
  note?: string;
  downloads: number[];
  cta?: ItemFeature_NoRelations;
  cta_btn?: Btn_NoRelations;
  seo?: SeoMeta_NoRelations;
}

export interface Resourcy_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  site_setting?: AdminPanelRelationPropertyModification<SiteSetting_Plain>;
  hero?: Hero_Plain;
  intro?: string;
  note?: string;
  downloads: AdminPanelRelationPropertyModification<Download_Plain>;
  cta?: ItemFeature_Plain;
  cta_btn?: Btn_Plain;
  seo?: SeoMeta_Plain;
}
